// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: reachability/v1/reachability.proto

package reachabilityv1

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on ReachableResourcesRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ReachableResourcesRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ReachableResourcesRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ReachableResourcesRequestMultiError, or nil if none found.
func (m *ReachableResourcesRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *ReachableResourcesRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetConsistency()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, ReachableResourcesRequestValidationError{
					field:  "Consistency",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, ReachableResourcesRequestValidationError{
					field:  "Consistency",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetConsistency()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return ReachableResourcesRequestValidationError{
				field:  "Consistency",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if all {
		switch v := interface{}(m.GetStartingResource()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, ReachableResourcesRequestValidationError{
					field:  "StartingResource",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, ReachableResourcesRequestValidationError{
					field:  "StartingResource",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetStartingResource()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return ReachableResourcesRequestValidationError{
				field:  "StartingResource",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	// no validation rules for TargetObjectType

	if len(errors) > 0 {
		return ReachableResourcesRequestMultiError(errors)
	}

	return nil
}

// ReachableResourcesRequestMultiError is an error wrapping multiple validation
// errors returned by ReachableResourcesRequest.ValidateAll() if the
// designated constraints aren't met.
type ReachableResourcesRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ReachableResourcesRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ReachableResourcesRequestMultiError) AllErrors() []error { return m }

// ReachableResourcesRequestValidationError is the validation error returned by
// ReachableResourcesRequest.Validate if the designated constraints aren't met.
type ReachableResourcesRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ReachableResourcesRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ReachableResourcesRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ReachableResourcesRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ReachableResourcesRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ReachableResourcesRequestValidationError) ErrorName() string {
	return "ReachableResourcesRequestValidationError"
}

// Error satisfies the builtin error interface
func (e ReachableResourcesRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sReachableResourcesRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ReachableResourcesRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ReachableResourcesRequestValidationError{}

// Validate checks the field values on ReachableResourcesResponse with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ReachableResourcesResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ReachableResourcesResponse with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ReachableResourcesResponseMultiError, or nil if none found.
func (m *ReachableResourcesResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *ReachableResourcesResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetFoundResource()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, ReachableResourcesResponseValidationError{
					field:  "FoundResource",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, ReachableResourcesResponseValidationError{
					field:  "FoundResource",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetFoundResource()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return ReachableResourcesResponseValidationError{
				field:  "FoundResource",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	// no validation rules for DirectPath

	if all {
		switch v := interface{}(m.GetFoundAt()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, ReachableResourcesResponseValidationError{
					field:  "FoundAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, ReachableResourcesResponseValidationError{
					field:  "FoundAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetFoundAt()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return ReachableResourcesResponseValidationError{
				field:  "FoundAt",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return ReachableResourcesResponseMultiError(errors)
	}

	return nil
}

// ReachableResourcesResponseMultiError is an error wrapping multiple
// validation errors returned by ReachableResourcesResponse.ValidateAll() if
// the designated constraints aren't met.
type ReachableResourcesResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ReachableResourcesResponseMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ReachableResourcesResponseMultiError) AllErrors() []error { return m }

// ReachableResourcesResponseValidationError is the validation error returned
// by ReachableResourcesResponse.Validate if the designated constraints aren't met.
type ReachableResourcesResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ReachableResourcesResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ReachableResourcesResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ReachableResourcesResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ReachableResourcesResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ReachableResourcesResponseValidationError) ErrorName() string {
	return "ReachableResourcesResponseValidationError"
}

// Error satisfies the builtin error interface
func (e ReachableResourcesResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sReachableResourcesResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ReachableResourcesResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ReachableResourcesResponseValidationError{}
